== Introduction

The _Dynamo Web Application Accelerator Framework_ is a software
development framework developed by https://www.opencirclesolution.nl[Open Circle Solutions]
that aims to  increase productivity by using design principles such as
convention over configuration, model-driven development and DRY (don’t
repeat yourself).

At the core of Dynamo is the concept of the _Entity Model_. The Entity
Model describes the attributes and behaviour of an entity (or domain
object) in your application. This Entity Model can then be used as the
basis for creating forms, tables, search screens etc.

The _Entity Model_ of an entity is automatically constructed based on
the properties of the attributes of the entity (using sensible defaults
as described by the convention over configuration principle) and can
further be modified by using annotations and message bundle entries. The
main goal is to reduce the amount of (boilerplate) code required to
perform common actions like creating search screens and edit forms.

Complementing the _Entity Model_ is a set of user interface components
(widgets) that can be used to quickly construct screens for common use
cases, and several base classes for the Data Access and Service layers.

The Dynamo framework is built around a number of proven and highly
productive technologies:

* https://jakarta.ee/specifications/persistence/[JPA3.1] for ORM
* https://querydsl.com[QueryDSL] for type-safe query generation
* https://docs.spring.io/spring-boot/index.html[Spring Boot] as the
application framework
* https://angular.dev[Angular (v16)] as the front-end framework of choice
* https://primeng.org[PrimeNG] for a rich suite of components

The Dynamo Framework is distributed under the terms of the
https://www.apache.org/licenses/LICENSE-2.0.txt[Apache License], a
permissive open-source license for free and open-source software (FOSS).

The sources of Dynamo can be found at https://github.com/opencirclesolutions/dynamo[Github].
