/**
 * GTS
 * Gift tracking 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Therequest containing the input and desired AI service
 */
export interface AutoFillRequest { 
    input: string;
    type: AutoFillRequest.TypeEnum;
    additionalInstructions?: string;
}
export namespace AutoFillRequest {
    export type TypeEnum = 'Bedrock' | 'Chat GPT (OpenAI)' | 'Google VertexAI' | 'Ollama';
    export const TypeEnum = {
        Bedrock: 'Bedrock' as TypeEnum,
        Chat_GPT__OpenAI: 'Chat GPT (OpenAI)' as TypeEnum,
        Google_VertexAI: 'Google VertexAI' as TypeEnum,
        Ollama: 'Ollama' as TypeEnum
    };
}


