/**
 * GTS
 * Gift tracking 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CascadeModel { 
    cascadeTo: string;
    filterPath: string;
    cascadeMode: CascadeModel.CascadeModeEnum;
}
export namespace CascadeModel {
    export type CascadeModeEnum = 'SEARCH' | 'EDIT' | 'BOTH';
    export const CascadeModeEnum = {
        SEARCH: 'SEARCH' as CascadeModeEnum,
        EDIT: 'EDIT' as CascadeModeEnum,
        BOTH: 'BOTH' as CascadeModeEnum
    };
}


