/**
 * GTS
 * Gift tracking 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttributeModelResponse } from './attributeModelResponse';
import { AttributeGroupResponse } from './attributeGroupResponse';
import { EntityModelActionResponse } from './entityModelActionResponse';


export interface EntityModelResponse { 
    attributeModels: Array<AttributeModelResponse>;
    attributeGroups: Array<AttributeGroupResponse>;
    attributeNamesOrdered: Array<string>;
    attributeNamesOrderedForGrid: Array<string>;
    attributeNamesOrderedForSearch: Array<string>;
    descriptions: { [key: string]: string; };
    displayNames: { [key: string]: string; };
    displayNamesPlural: { [key: string]: string; };
    displayProperty?: string;
    reference?: string;
    sortProperty: string;
    sortAscending: boolean;
    deleteAllowed: boolean;
    listAllowed: boolean;
    createAllowed: boolean;
    updateAllowed: boolean;
    exportAllowed: boolean;
    actions?: Array<EntityModelActionResponse>;
    readRoles?: Array<string>;
    writeRoles?: Array<string>;
    deleteRoles?: Array<string>;
}

