/**
 * GTS
 * Gift tracking 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FilterModel { 
    match: FilterModel.MatchEnum;
    name?: string;
}
export namespace FilterModel {
    export type MatchEnum = 'EQUALS' | 'DATE_RANGE' | 'NUMBER_RANGE' | 'INSTANT_RANGE' | 'LOCAL_DATE_TIME_RANGE' | 'NUMBER_IN' | 'TIME_RANGE' | 'OR' | 'NOT';
    export const MatchEnum = {
        EQUALS: 'EQUALS' as MatchEnum,
        DATE_RANGE: 'DATE_RANGE' as MatchEnum,
        NUMBER_RANGE: 'NUMBER_RANGE' as MatchEnum,
        INSTANT_RANGE: 'INSTANT_RANGE' as MatchEnum,
        LOCAL_DATE_TIME_RANGE: 'LOCAL_DATE_TIME_RANGE' as MatchEnum,
        NUMBER_IN: 'NUMBER_IN' as MatchEnum,
        TIME_RANGE: 'TIME_RANGE' as MatchEnum,
        OR: 'OR' as MatchEnum,
        NOT: 'NOT' as MatchEnum
    };
}


