/**
 * GTS
 * Gift tracking 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FilterModel } from './filterModel';


export interface NumberInFilterModel extends FilterModel { 
    values: Array<number>;
}
export namespace NumberInFilterModel {
}


