/**
 * GTS
 * Gift tracking 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PagingModel { 
    pageNumber: number;
    pageSize: number;
    type: PagingModel.TypeEnum;
}
export namespace PagingModel {
    export type TypeEnum = 'INHERIT' | 'PAGING' | 'ID_BASED';
    export const TypeEnum = {
        INHERIT: 'INHERIT' as TypeEnum,
        PAGING: 'PAGING' as TypeEnum,
        ID_BASED: 'ID_BASED' as TypeEnum
    };
}


