/**
 * GTS
 * Gift tracking 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SearchModelFiltersInner } from './searchModelFiltersInner';
import { SortModel } from './sortModel';
import { PagingModel } from './pagingModel';


/**
 * The search request
 */
export interface SearchModel { 
    paging: PagingModel;
    sort: SortModel;
    filters?: Array<SearchModelFiltersInner>;
}

