/**
 * GTS
 * Gift tracking 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AbstractEntity } from './abstractEntity';
import { StatsModel } from './statsModel';


export interface SearchResultsModelAbstractEntity { 
    stats?: StatsModel;
    results?: Array<AbstractEntity>;
}

