/**
 * GTS
 * Gift tracking 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LocalTime } from './localTime';
import { FilterModel } from './filterModel';


export interface TimeRangeFilterModel extends FilterModel { 
    from?: LocalTime;
    to?: LocalTime;
}
export namespace TimeRangeFilterModel {
}


