CREATE TABLE MOVIE(ID IDENTITY PRIMARY KEY, TITLE VARCHAR(255), RELEASE_DATE DATE, IMDB_URL VARCHAR(255), 
	ACTION BIT, ADVENTURE BIT, ANIMATION BIT, KIDS BIT, COMEDY BIT, CRIME BIT, DOCUMENTARY BIT, DRAMA BIT, FANTASY BIT,
    FILM_NOIR BIT, HORROR BIT, MUSICAL BIT, MYSTERY BIT, ROMANCE BIT, SCI_FI BIT, THRILLER BIT, WAR BIT, WESTERN BIT, VERSION INT);