CREATE TABLE COUNTRY(ID IDENTITY PRIMARY KEY, NAME VARCHAR(255), VERSION INT);

CREATE TABLE MOVIE(ID IDENTITY PRIMARY KEY, TITLE VARCHAR(255), RELEASE_DATE DATE, IMDB_URL VARCHAR(255), GROSS DECIMAL(12,2), MPAA_RATING VARCHAR(8), DOCUMENTARY BIT, COUNTRY_ID BIGINT, VERSION INT, FOREIGN KEY(COUNTRY_ID) REFERENCES COUNTRY(ID));

CREATE TABLE TAG(ID IDENTITY PRIMARY KEY, NAME VARCHAR(255), MOVIE_ID BIGINT, VERSION INT, FOREIGN KEY(MOVIE_ID) REFERENCES MOVIE(ID));

